export const SYNC_GAME_DATA_ACTION = 'SYNC_GAME_DATA_ACTION'
export const SYNC_GAME_MODES_ACTION = 'SYNC_GAME_MODES_ACTION'
export const GAMES_IS_LOADING = 'GAMES_IS_LOADING'

export const MAKE_MOVE_ACTION = 'MAKE_MOVE_ACTION'
export const IS_SENDING_ACTIVE_GAME_ACTION = 'IS_SENDING_ACTIVE_GAME_ACTION'